version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gosec
  exclusions:
    rules:
      - linters:
          - gosec
        text: "G201|G202"

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    excludes:
      - G301
      - G304
